# SPDX-FileCopyrightText: (c) TagStudio Contributors
# SPDX-License-Identifier: CC0-1.0
---
name: Release

on:
  push:
    tags:
      - nightly
      - prerelease
      - release
      - v*
  schedule:
    # From: https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#schedule
    # To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
    - cron: 42 3 * * *
      timezone: America/Los_Angeles
  workflow_dispatch:
    inputs:
      draft:
        description: Mark as draft
        type: boolean
        default: true
      type:
        description: Release type
        type: choice
        options:
          - Nightly
          - Pre-Release
          - Release
        default: Nightly
      bump:
        description: |-
          SemVer version bump
          'None' is relevant for Nightly and Pre-Release, where the metadata is bumped
        type: choice
        options:
          - None
          - Patch
          - Minor
          - Major
        default: None

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metadata:
    defaults:
      run:
        shell: sh

    name: Metadata
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.original }}
      version-base: ${{ steps.metadata.outputs.version-base }}
      version-prerelease-identifier: placeholder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Get version context
        id: version
        env:
          VERSION_REF: >-
            ${{ case( github.ref_type == 'tag' && startsWith(github.ref_name, 'v'), github.ref_name, '') }}
        run: |
          version=${VERSION_REF:-$(git tag -l --sort=-v:refname 'v*' | head -n 1)}
          cat <<EOF >"${GITHUB_OUTPUT}"
          original=${version}
          segments=$(scripts/semver-segments.pl "${version#v*}")
          EOF

      - name: Parse SemVer version segments
        id: version-segments
        env:
          VERSION_SEGMENTS: ${{ steps.version.outputs.segments }}
        shell: bash
        run: |
          if type -t readarray >/dev/null; then
              readarray -t version_segments <<<"${VERSION_SEGMENTS}"
          else
              version_segments=()
              while IFS= read -r segment; do
                  version_segments+=("${segment}")
              done <<<"${VERSION_SEGMENTS}"
          fi

          cat <<EOF >>"${GITHUB_OUTPUT}"
          0=${version_segments[0]}
          1=${version_segments[1]}
          2=${version_segments[2]}
          3=${version_segments[3]:-}
          4=${version_segments[4]:-}
          EOF

      - name: Set metadata
        id: metadata
        env:
          VERSION_DO_BUMP: >-
            ${{ !(github.event == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')) }}

          VERSION_MAJOR: ${{ steps.version-segments.outputs.0 }}
          VERSION_MINOR: ${{ steps.version-segments.outputs.1 }}
          VERSION_PATCH: ${{ steps.version-segments.outputs.2 }}
          VERSION_PRERELEASE: ${{ steps.version-segments.outputs.3 }}
          VERSION_BUILDMETADATA: ${{ steps.version-segments.outputs.4 }}
        run: |
          version_major=${VERSION_MAJOR}
          version_minor=${VERSION_MINOR}
          version_patch=${VERSION_PATCH}
          version_prerelease=${VERSION_PRERELEASE}
          version_buildmetadata=${VERSION_BUILDMETADATA}

          if [ "${VERSION_DO_BUMP}" = true ]; then
            case ${INPUT_BUMP:-} in
            None | '') ;;
            Patch) version_patch=$((version_patch + 1)) ;;
            Minor) version_minor=$((version_minor + 1)) ;;
            Major) version_major=$((version_major + 1)) ;;
            esac
          fi

          cat <<EOF >>"${GITHUB_OUTPUT}"
          version-base=${version_major}.${version_minor}.${version_patch}
          version-prerelease=${version_prerelease}
          version-buildmetadata=${version_buildmetadata}
          EOF

  release:
    permissions:
      contents: write

    name: Create Release
    needs: metadata
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.type != 'Release' }}
          title: >-
            Alpha v${{ needs.metadata.outputs.version-base }}
            ${{ needs.metadata.outputs.type && format(' {0}', needs.metadata.outputs.type) }}
            ${{ needs.metadata.outputs.version-prerelease-identifier && format(' {0}', needs.metadata.outputs.version-prerelease-identifier) }}
